steps:
  # Install dependencies and deploy Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy listBucketsFunction \
          --entry-point=list_buckets \
          --runtime=python310 \
          --trigger-http \
          --no-allow-unauthenticated \
          --set-env-vars=GOOGLE_PROJECT=kilo-gcp \
          --region=us-central1 \
          --service-account=779291354937-compute@developer.gserviceaccount.com
          

options:
  logging: CLOUD_LOGGING_ONLY

# Permissions for Cloud Build service account
serviceAccount: 779291354937-compute@developer.gserviceaccount.com
